# ros_gz_bridge: 3D lidar
- ros_topic_name: "/hyperdog/lidar/points"
  gz_topic_name: "hyperdog/lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
