# ros_gz_bridge: RGB-D camera
- ros_topic_name: "/hyperdog/camera/image"
  gz_topic_name: "hyperdog/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/hyperdog/camera/depth_image"
  gz_topic_name: "hyperdog/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/hyperdog/camera/points"
  gz_topic_name: "hyperdog/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
- ros_topic_name: "/hyperdog/camera/camera_info"
  gz_topic_name: "hyperdog/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
